### ISSUE TITLE
[FEATURE] - settings page with sub sections? 

### ISSUE THREAD

**Issue by Nejcc** [tabler/tabler#1070]
is there any plan for settings page ?
 - personal info
 - data & privacy
 - security
 - people & sharing
 - passwords ...
 - payment and subscription... 

@codecalm

**Comment by Nejcc** [comment]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/6236128/155856310-fb939b58-c581-4eab-a396-187baedba1a0.png">

**Comment by rjd22** [comment]
@Nejcc there are no plans for such a page. Would you like to design one for us and contribute it?

**Comment by kevinpapst** [comment]
@rjd22 can be closed as this was added recently https://preview.tabler.io/settings.html

Unfortunately it looks terrible with overlapping navigation ... but that is for another issue.

**Comment by rjd22** [comment]
@kevinpapst What would be a good way to improve it?

**Comment by kevinpapst** [comment]
I guess the user who contributed the settings page did not test overlapping navigation and the merger didn't either.

This is how it looks, simply unusable: 
<img width="1349" alt="Bildschirmfoto 2022-07-30 um 20 47 46" src="https://user-images.githubusercontent.com/533162/181937434-b310beaf-299c-4410-9223-f522eefcb4dc.png">

I am not sure if Tabler aims to support every component in every page style, that's why I never opened an issue.
But it prevented me from using it, as my users can switch between "full page with vertical navigation" and "centered page with overlapping navigation" and as you can see: it doesn't work with overlapping navigation. 

Regarding your question "a good way to improve it": I don't know. I'd be glad if I had good frontend skills. The only idea I have is pushing the content down somehow.

**Comment by rjd22** [comment]
IMO that seems like a bug. I will take a look at that since I like to support as much as possible. Ofcourse with all the different mixes and matches this is really hard to test but pages should work properly with all navigation versions.

**Comment by dheineman** [comment]
Using the overlapping navigation, all other pages that do not put content like that in a card will have this problem. 

The search results page shows a similar problem.
![Screenshot 2022-08-01 at 09 18 19](https://user-images.githubusercontent.com/516028/182093964-2ccd9b4b-7d4c-44f0-b2fa-be147109c71c.png)

A possible solution for the settings page is moving the menu into a card.
![Screenshot 2022-08-01 at 10 27 57](https://user-images.githubusercontent.com/516028/182106808-4f478999-3118-4d97-b274-7db8ed2bf930.png)


Or having a single page/card with all settings like this.
![Screenshot 2022-08-01 at 10 24 05](https://user-images.githubusercontent.com/516028/182106109-dfbd726b-83cc-4fe0-b0e2-28e074534b03.png)

**Comment by kevinpapst** [comment]
True.
In my case the settings page is really long, horizontal tabs are not working (too many) and vertical tabs are not existing (without javascript workaround).
But you upper card solution looks okay'ish 👍 I will give it a try.

**Comment by kevinpapst** [comment]
Yep, I saw the changes, but forgot about the issue. Thanks for taking care @rjd22 and @dheineman !
