### ISSUE TITLE
[BUG] Active state on button doesn't work

### ISSUE THREAD

**Issue by MrSquaare** [tabler/tabler#1170]
**Describe the bug**

Adding `.active` class or `:active` doesn't render the button as active

**Device**

 - Browser: Firefox 102
 - OS: Ubuntu 20.04
 - Screen size: 1920x1080

**To reproduce**

1. Setup a projet with `@tabler/core@1.0.0-beta10`
2. Add a button with `.active` class
3. The button keep no state style

**Comment by dheineman** [comment]
I have the same issue in my project but both the `.active` class and `:active` state seem to trigger just fine on preview.tabler.io so i assume this is already fixed in main but no new version which includes the fix has been released yet.

![tabler_active](https://user-images.githubusercontent.com/516028/181511074-25907182-61b0-458e-aa21-55d54fe11361.png)
