### ISSUE TITLE
[FEATURE] Quill JS integration in Tabler

### ISSUE THREAD

**Issue by cavasinf** [tabler/tabler#1274]
**Is your feature request related to a problem? Please describe.**
We've switch form TinyMCE to [Quill JS](https://quilljs.com/) to be able to add [mentions](https://github.com/quill-mention/quill-mention) `@someone` inside text rich input.

But QuillJs style is not ready for Tabler.

**Describe the solution you'd like**
Can you provide styles for Quill inside Tabler

**Describe alternatives you've considered**
I've added custom style on my side to look like Tabler template:

![image](https://user-images.githubusercontent.com/25293190/191679722-7eb33865-812e-4e4a-9fdf-535ed01b8644.png)

```sass
.ql-toolbar + .ql-container {
  border-top: 0 !important
  border-radius: 0 0 4px 4px
}

.ql-toolbar, .ql-container {
  border: 1px solid #d9dbde !important
}

.ql-toolbar {
  border-radius: 4px 4px 0 0
}

.ql-container {
  border-radius: 4px
}
```

**Comment by rjd22** [comment]
There are so many rich text editors out that that we won't be able to support them all. I've been using CKEditor with tabler without big restyles. Quill also didn't get a new version since 2019 so I think we won't be supporting it if the maintainer doesn't support the editor.

Building your own custom CSS changes to support external modules is a fine way to solve this problem ;)

**Comment by cavasinf** [comment]
Hey @rjd22, Quill 2.0 is out and [LaravelBackpack ](https://github.com/laravel-backpack/crud) (which use Tabler) use this WYSIWYG.
Is this enough to think about integrate templating/css for this plugin?
