### ISSUE TITLE
[BUG] Dropdown menu in single-row tables not displaying correctly

### ISSUE THREAD

**Issue by tarunvelli** [tabler/tabler#1343]
**Describe the bug**

When a table container a single row, and the row contains a dropdown menu, the dropdown menu is displayed incorrectly. I would expect the dropdown menu to "pop out" from the table instead of requiring to scroll in the table.

**Device**

 - Browser: Chrome Version 106.0 & Firefox Version 106.0
 - OS: macOS Monterey
 - Screen size: 3456 × 2234

**To reproduce**

1. Delete all rows except 1 in a table with dropdown example
2. Click on dropdown

**Screenshots**

https://user-images.githubusercontent.com/19463001/199216244-f7c44a7c-1d82-4566-a38e-0b23c99f98f5.mov

**Comment by rjd22** [comment]
@tarunvelli This is expected behavior with tables the `table-responsive`. When fields don't fit on mobile it makes the tables scrollable. Sadly this means that when there is no room for the action box it also becomes scrollable.

you have 3 ways to solve this:
1: Give the table a min-height to make accommodate the size for the dropdown.
2: Remove the table-responsive class so the dropdown overflows
3: Use normal buttons and completely remove the dropdowns.

@codecalm What do you think?

**Comment by codecalm** [comment]
unfortunately it's expected behaviour :( until dropdown-menu is assigned inside `.table-responsive` it's impossible to show dropdown outside :(

**Comment by humbertleonardo** [comment]
Apparently I managed to solve the problem. I followed these steps

1. Add the "position-fixed" class next to "dropdown-menu dropdown-menu-end";
2. Remove the 'data-bs-boundary="viewport"' class from the button.


Your code will look like this:

![image](https://github.com/tabler/tabler/assets/57204453/d5ae9cc8-7c48-478d-b8f1-1b92db9418d9)
