### ISSUE TITLE
[BUG] blinking the template while the dark theme is on and clicking on links

### ISSUE THREAD

**Issue by DifficultPhil** [tabler/tabler#1576]
**Describe the bug**

I use table together with laravel. if you were going to turn on the dark theme and navigate through the pages of the site, then a light theme will turn on for a second, and then immediately dark, this happens on all pages

**Device**

 - Browser chrome 159, chrome mobile
 - OS: Windows 10, android 13
 - Screen size fullhd

Version tabler - 1.0.0-beta17

Video demonstrate - https://youtube.com/shorts/3CHUTzBXuoI?feature=share

**Comment by dheineman** [comment]
This most likely happens because you are loading the code that checks and switches to the users theme preference too late.

[preview.tabler.io](https://preview.tabler.io/) also had this problem and i fixed it with https://github.com/tabler/tabler/pull/1176 by loading the theme code directly after the body open tag.

**Comment by kevinpapst** [comment]
You are using Laravel, you can also switch the theme in your backend code (e.g. store it in the session or user-preference).
