### ISSUE TITLE
[FEATURE] htmx

### ISSUE THREAD

**Issue by gedw99** [tabler/tabler#1695]
**Is your feature request related to a problem? Please describe.**

Building static html is solved well.

but as soon as you need to build larger systems that are reactive you hit the wall of es the , vue etc and you hit the SEO problem too because you will get down ranked by google due to speed of loading .

htmx solves this

Easy to extend so that a page can use simple meta tags to manage actions and have the psge parts update using html rendered on the server.

htmx is Open and gaining devotees sick of the lock-in to complex spa approaches.

it’s a good match for this project and it’s developer skill set too I feel.

**Describe the solution you'd like**

Support for htmx so that it’s easy to update the page.

**Describe alternatives you've considered**

I find react etc too non web and complex.

**Comment by rjd22** [comment]
I understand that everyone want his own favorite system to be supported but that is not how tabler works. Tabler gives to the tooling needed to build your own application how you want, using the tooling that you like.

We're not going to support every framework out of the box because this will force use to maintain those implementations while we're not using them. For that reason I'm going to close this.

**Comment by gedw99** [comment]
Totally understand
