### ISSUE TITLE
[BUG] the drop-down menu opens in the wrong place, but it becomes correct after scrolling the screen.

### ISSUE THREAD

**Issue by nowlights** [tabler/tabler#1744]
### Browser

Edge

### OS

Windows 11

### Screen size

1920x1080

### Describe the bug

Before scrolling

![image](https://github.com/tabler/tabler/assets/57915897/60ac1d41-2dd2-4723-8766-a9e1e46954af)

After scrolling screen
![image](https://github.com/tabler/tabler/assets/57915897/ebc38f5e-4411-4b65-a06c-b657c506dd21)

I using with Blazor Wasm

(Maybe it's miscalculating the button size? because of the blazor?)

**Comment by nowlights** [comment]
More details:

before scrolling:

![image](https://github.com/tabler/tabler/assets/57915897/40b0ca76-17f2-41e7-bd6f-99bccc186255)


after scrolling:

![image](https://github.com/tabler/tabler/assets/57915897/294efff8-8e5e-40d1-a5ec-5c809aa063a0)

**Comment by rjd22** [comment]
Chances are this is a je library incompatibility that has nothing to do with tabler. Since tabler uses Bootstrap under water there is not much we can do here.

If you have a really specific case that you can point to tabler js or scss feel free to reopen but for now I'm closing this as not actionable.
