### ISSUE TITLE
Select 2 bug

### ISSUE THREAD

**Issue by danieljsc** [tabler/tabler#200]
First of all, thanks for the template. The look is really amazing, but after a few tests trying to include some well known libraries my hype is coming down.

Modal/Alerts close buttons are duplicated, and Select2 library is not working well also as you can see in the next image:
![image](https://user-images.githubusercontent.com/23213576/45590307-a2c0a080-b92d-11e8-926c-141ff9969a71.png)

Had to increase Z-Index on select2 and well.... the look of it.
I know this might be css issues (I'm not good at all at that level)

**Comment by keshon** [comment]
Tabler is bundled with Selectized and works flawlessly with that. I hardly doubt it's Tabler's issue rather than Select2 or Bootstrap itself.

**Comment by camalsoft** [comment]
This issue occurs because modals tend to steal focus from other elements outside of the modal. Since by default, Select2 attaches the dropdown menu to the <body> element, it is considered "outside of the modal". For fixit this bug add setting "dropdownParent" in Select2 setting.

$('#userSkill').select2({
 dropdownParent: $('#SkillsModal')
});
