### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by cserko93** [tabler/tabler#241]
Please make a dark css template file for it.

**Comment by vaga** [comment]
> Hi @thiagorp
> I'm working on Tabler 1.0 version. Probably will be published until end of this year. New Tabler will be with dark theme, light/dark sidebar and with many, many improvements :)
https://github.com/tabler/tabler/issues/184#issuecomment-417568142

:crossed_fingers:

**Comment by codecalm** [comment]
Dark theme will be avaliable in 1.0 version :)

**Comment by h-guerrero** [comment]
Is this feature already launched?

**Comment by dhavenith** [comment]
> 
> 
> Is this feature already launched?

I hope so. I'm currently looking for it

**Comment by earboxer** [comment]
It doesn't look like it uses [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) :(

**Comment by codecalm** [comment]
@earboxer tabler uses media prefer-color-scheme styles. Replace `.theme-dark` to `.theme-dark-auto`

**Comment by earboxer** [comment]
I can't get it to work. I'm doing 

```html
<body class='theme-dark'>
```

Is this wrong?

**Comment by codecalm** [comment]
no, but `theme-dark` uses only dark theme, without media prefer-color-scheme styles

**Comment by earboxer** [comment]
Ah, I think the problem was I was using `1.0.0-alpha.3`, which is ca79aa308, and doesn't have the dark theme in the compiled css.

I got it to work by switching my dependency version to `"tabler": "github:tabler/tabler#ff5e69da"` in package.json. (I guess this is what I get for wanting the bleeding edge of development :)

Thanks for your awesome and beautiful library, and for your quick response as well!

**Comment by codecalm** [comment]
@earboxer I've released version 1.0.0-alpha.4 - now should work :)

**Comment by JordanTAdelman** [comment]
Hey @codecalm I have a question regarding Dark Mode for Tabler.io. When it comes to implementing it you stated you need to change the ```.theme-dark``` to ```.theme-dark-auto``` Do I need to also do what @earboxer did, ```"tabler": "github:tabler/tabler#ff5e69da"```, to implement this change?

**Comment by tjarbo** [comment]
Hi @JordanTAdelman 

> Do I need to also do what @earboxer did, "tabler": "github:tabler/tabler#ff5e69da", to implement this change?

it is not required anymore to pin the tabler.io version in order to use the dark mode feature 🎉 just install/use the latest release.

---

In order to use the dark theme, you have two options:
1. using `<body class="theme-dark-auto">..</body>` enables/disables the dark mode based on the system settings set by the user. Compare this with the[ "Sync with system" feature provided by GitHub](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/managing-your-theme-settings). It uses the `prefers-color-scheme media query` ([caniuse.com](https://caniuse.com/prefers-color-scheme)).
2. using `<body class="theme-dark">..</body>` will enforce the dark theme on your website. And of course, if you want to switch back to light theme/mode, you have to remove the CSS class.

Hope this helps :)

**Comment by TrendSonic** [comment]
Hi everyone,
I have a problem with dark theme on tabler when updated newset version 1.0.0 - beta16.
Seems like its not setting a class to body element when clicked on link and its not setting tablerTheme to local storage either, what is the problem here?
