### ISSUE TITLE
Wrong type of $grid-gutter-width

### ISSUE THREAD

**Issue by WinterSilence** [tabler/tabler#261]
$grid-gutter-width defined in https://github.com/twbs/bootstrap/blob/master/scss/_variables.scss using to calculate container width: `container-max-width = grid-breakpoint - (grid-gutter-width * 2)`. You cant set breakpoints as px and $grid-gutter-width as rem: size of rem in px independent of screen size - u can set any font size for any screen size in browser settings.

**Comment by mendozagioo** [comment]
I want to help, but I don't understand the problem.
First of all, `$grit-gutter-width` doesn't used to calculate `$container-max-width`, in fact doesn't exist, because exist: `$container-max-widths` that is a set of sizes by default, defined in `_variables.scss`. Can you explain more about this? @WinterSilence

**Comment by WinterSilence** [comment]
@mendozagioo
