### ISSUE TITLE
datatables not working

### ISSUE THREAD

**Issue by 4NG3L1337** [tabler/tabler#336]
In the demo page data tables works well but when i download the template from tabler.io (download button) this version don't have the css for data tables and the plugin for datatable, how i can fix this  thank you!! and i love your work guys!

**Comment by pess0a** [comment]
i copied databoard.css from hosted source and pasted into my file
and then it works.

**Comment by AntonLoktionov** [comment]
please, someone share actual version of rendered html with datatables

**Comment by frdhont** [comment]
I managed to add the plugin and css from the DataTables website, however this results in the table not being generated in the tabler.io lay-out. When I add the dashboard.css from the tabler.io website, the DataTable is printed correctly, but my divs are all messed up.

**Comment by afbora** [comment]
Can someone say how it works for v1.0.0-alpha.7? 🤔

**Comment by DMW007** [comment]
I'm using the server side option of DataTables so that only the currently displayed page is rendered. This works on the page load, but after I type something into the search there is a "processing" splashscreen which doesn't disapear after the data is fetched with ajax:

![grafik](https://user-images.githubusercontent.com/21245043/108611247-14de1f00-73dd-11eb-89cd-9aba165ae64d.png)

It seems that those problems occurs because [tabler want to get rid of the dependency to jQuery](https://github.com/tabler/tabler/issues/749#issuecomment-751453493). As I [already wrote there](https://github.com/tabler/tabler/issues/749#issuecomment-782841379) I think this is a good thing, as long as it doesn't have negative effects on the features.

**Comment by afbora** [comment]
@codecalm What do you think about using `List.js` instead of `DataTables` in the new version? 

GitHub Repository
https://github.com/javve/list.js

Website
https://listjs.com/

**Comment by rjd22** [comment]
Closing this issue since there already is a feature request issue for Datatables https://github.com/tabler/tabler/issues/905

**Comment by rsyafdhil** [comment]
did tabler hide the colvis button? cuz when i was styling my website with tabler, the colvis button wont showing again. Before i styled it with tabler, the colvis button showing up.
