### ISSUE TITLE
Support composer

### ISSUE THREAD

**Issue by roanvanbao** [tabler/tabler#42]
#46

**Comment by codecalm** [comment]
Hi @roanvanbao, do you have any ideas how it should works?

**Comment by Nilpo** [comment]
@roanvanbao This isn't a PHP project.

**Comment by roanvanbao** [comment]
I'm building a Laravel library. I want it support composer so that I can add it as dependency. When it changes, I don't need to copy all files from it to my library. In other words, I want my library always up-to-date without copy files. Thank you!

**Comment by codecalm** [comment]
@roanvanbao merged
check is everything ok

**Comment by roanvanbao** [comment]
Thank you. Can you submit it to [packagist](https://packagist.org/packages/submit)?

**Comment by codecalm** [comment]
done: https://packagist.org/packages/tabler/tabler

**Comment by roanvanbao** [comment]
Yeah! Awesome!

**Comment by codecalm** [comment]
you're welcome

**Comment by snipe** [comment]
@roanvanbao Hey there, sorry to frankenthread!

Can you tell me how this would be integrated into a Laravel project? I don't see any related vendor files to publish, so I'm not exactly sure how to make this work. I've been (very messily) trying to manually integrate it with app.js and bootstrap.js from the out of the box Laravel 5.6 install, but it's going pretty badly, since they both use bootstrap and jquery. I'm not super awesome at making webpack/mix bend to my will on a good day, so I'm a little confused.

Thanks so much for any insight you can give! ❤️ 

And thanks SO much for a great UI kit, @codecalm! ❤️

**Comment by roanvanbao** [comment]
@snipe You can use it. https://packagist.org/packages/pingecom/l5-tabler

**Comment by twf-nikhila** [comment]
Does anyone use it in Laravel application without any package?
