### ISSUE TITLE
The freshest preview-dev has small bugs

### ISSUE THREAD

**Issue by kicaj** [tabler/tabler#480]
Dropdowns:
1. Dropdowns (eg. from nav menu) remains open when we open new ones;
2. Dropdowns from tables (at the bottom of the home page) are fixed when scrolling up;

3. https://preview-dev.tabler.io/buttons.html - In Standard buttons, "secondary" buttons are broken to two lines;
4. https://preview-dev.tabler.io/profile.html - Profile of Flossi Uttley;
5. Links from Docs nav menu doesn't works;
6. https://preview-dev.tabler.io/snippets.html - Card with header "Tabler UI" and "Tabler React" aren't display correct;
7. https://preview-dev.tabler.io/users.html - Button "+ New user" is broken to two lines.
8. There is no profile avatar in navbar.

**Comment by codecalm** [comment]
thank you for feedback, I'll check it!

**Comment by thewebartisan7** [comment]
@codecalm Any idea when the new version will be stable?

**Comment by kicaj** [comment]
Point 5 and 7 now works correctly.

**Comment by Huu-tu** [comment]
yes

**Comment by FreexD** [comment]
@kicaj thanks for heads up. It took some time but we managed to fix the issues ;)

1. Works fine in 1.0.0-alpha.14 - dropdowns in menu now close when opening new ones,
2. Fixed in #650 ,
3. Works fine in 1.0.0-alpha.14,
4. Profiles page got removed from 1.0.0 major - look at https://preview.tabler.io/widgets.html, https://preview.tabler.io/users.html instead,
5. Works fine in 1.0.0-alpha.14,
6. https://preview-dev.tabler.io/snippets.html has been moved to https://preview-dev.tabler.io/widgets.html for 1.0.0 major - works fine there,
7. Works fine in 1.0.0-alpha.14,
8. Works fine in 1.0.0-alpha.14,
