### ISSUE TITLE
[FEATURE] New Select Component

### ISSUE THREAD

**Issue by afbora** [tabler/tabler#625]
**Is your feature request related to a problem?**
[Selectize](https://github.com/selectize/selectize.js) is no longer developed (Latest version as v0.12.6 released  on 13 Jul 2018 and latest commit was submitted at 21 Nov 2018) and there are more than 500 issues.

**Describe the solution you'd like**
I would like using [Select2](https://github.com/select2/select2) which is actively developed and frequently used with bootstrap. instead of Selectize.

**Comment by ollym** [comment]
I agree, but this one is better:
https://github.com/JedWatson/react-select

**Comment by FreexD** [comment]
`react-select` will only work for React users. Tabler should also cover other frameworks ;) `Select2` however is jQuery based and Tabler is trying to get rid of jQuery for v1 since bootstrap doesn't use jQuery anymore in v5. 

That said I agree that replacing `Selectize` is a must ;) Any other propositions of selects tabler might use?

**Comment by aditya5660** [comment]
@FreexD you can use [Choices JS](https://github.com/jshjohnson/Choices) Vanilla Javascript or [Select2](https://select2.org/)

**Comment by oyejorge** [comment]
@FreexD there's also an updated and vanilla js fork of selectize: [tom-select](https://tom-select.js.org/)

**Comment by ollym** [comment]
@oyejorge https://github.com/orchidjs/tom-select actually looks really good. I know recently @codecalm twiced to Choices JS but that still isn't ideal because it is no longer maintained. @codecalm maybe tom-select is worth considering instead? What do you think?

**Comment by oyejorge** [comment]
@ollym glad you like it. I created [a tabler fork with tom-select](https://github.com/oyejorge/tabler/commit/785dae9194e08e08845c88905371d4e4a6856b7a) to see how it would work. There are a couple css changes still needed (caret, is-valid) but so far, so good.

**Comment by ronaldtveen** [comment]
Doing some research but Tom Select does look like a good contender. So many others either are jQuery based or no longer maintained. There is a risk in depending on quite a young code base, but I don't see a better alternative either. Plus, since it is a fork of selectize.js I guess it has a pretty solid foundation.

Got my vote.

**Comment by rjd22** [comment]
Tom select has now been integrated with Tabler.
