### ISSUE TITLE
How to run tabler in apache

### ISSUE THREAD

**Issue by linuxaos** [tabler/tabler#680]
Hello everyone,

Can I run tabler within Apache ? In other words, I already have Apache running and service content.
I want to add tabler pages. Can I do this?

Your help is most appreciated.

George

**Comment by colorninja** [comment]
Hello George,

Tabler is a front-end library.
Apache is a HTTP request server.

You need to build an application, serving HTML pages (through HTTP) and the Tabler assets in order to run it. There are a endless ways to do that and how to to this is a broad topic.

I would personally recommend looking into HTML, CSS, JavaScript and NodeJS tutorials to build your application, which could include Tabler.

**Comment by linuxaos** [comment]
Thank you for the quick reply. Is there a tutorial on how to get tabler up and running with a simple dashboard that requests updates from the server ? I am new to this and this would help me a great deal.
Thanks in advance.
