### ISSUE TITLE
Little help please

### ISSUE THREAD

**Issue by linuxaos** [tabler/tabler#692]
Hello everyone,
Please excuse the newbie question here but here goes:

The tabler demo is beautiful. I'd like to get started with tabler as well.
I need to get started with a simple project.
For instance, the Revenue widget from the demo.

I just need a simple page, with the revenue widget and when the page refreshes, I want it to show new numbers.
That's it. That would get me started. Right now I am not really sure I am doing the right thing.
I change the values of the revenue.html page and I see the change in the demo page.
Is this how it's done? Please forgive my lack of insight on this.

When I run: "npm run start" how does it get to the demo pages?
How can I tell it to go to my own pages? 
I am sorry but I don't see a HOWTO on my simple getting started.
I promise to create one when I'm done.

**Comment by colorninja** [comment]
Hi @linuxaos,

> When I run: "npm run start" how does it get to the demo pages?

There are multiple stages involved in this process. It compiles SCSS and JS files. Afterwards, it uses Jekyll to build all the HTML pages. The templates for those can be found in the pages folder.

> How can I tell it to go to my own pages?

You can edit the generated HTML, or the files used to generate pages. Alternatively you can create a website that renders HTML and includes the CSS/JS assets for Tabler.

> I am sorry but I don't see a HOWTO on my simple getting started.

I think that you have fundamentally wrong idea of what Tabler is. It is just UI, meaning it has 0 functionality behind it, unless you programme it yourself! There is no HOWTO, because this layout can be used in million ways. You **MUST** learn basic web development to be able to make it work.

> I just need a simple page, with the revenue widget and when the page refreshes, I want it to show new numbers.

As I said Tabler is UI only. It does not know how to fetch numbers You need to develop an application that would fetch the numbers and render the HTML markup Tabler requires.
