### ISSUE TITLE
laravel project

### ISSUE THREAD

**Issue by yjungles** [tabler/tabler#699]
I have a project using laravel 8 stack with bootstrap 5
I really liked the UI components of the tablr and would like to use them in my project.
What would be the best way?

should i just insert js and css in my layout?
is there a way to integrate tabler without using ruby?

**Comment by colorninja** [comment]
In my opinion, the best way would be to use npm/yarn to install it and then importing the scss/js files into Laravel Mix.
The (default) source files for Laravel projects can be found at `./resources/js/app.js` and `./resources/sass/app.scss` in the project root folder.

However keep in mind you will be running an old version, because new versions haven't been released since 20 April 2020. I have been advocating to release more frequently in #691 

The differences can be found here:
https://preview.tabler.io/
https://preview-dev.tabler.io/

**Comment by yjungles** [comment]
thank you for your generosity!
