### ISSUE TITLE
Form helpers [BUG] 

### ISSUE THREAD

**Issue by satiroglu** [tabler/tabler#756]
**Describe the bug**

First of all, thank you for your great work!
I just noticed a bug in **Documentation** part in [Form helpers](https://preview.tabler.io/docs/form-helpers.html) page. You  indicated on the related page as below:

_Use an input helper to display additional information about a form element. **The text label will appear once a user hovers over the helper**._

But does not work. Notthing happens. I hope I am not missing something. You can see the screenshot as below without cursor. 

**Tested Device**

 - Browser Google Chrome
 - OS: Windows 10

**Screenshots**

![image](https://user-images.githubusercontent.com/4512264/103393824-ea3abd00-4b35-11eb-9631-167cbd2c8674.png)

**Comment by FreexD** [comment]
@satiroglu thanks for reporting! will be fixed in new version :)

**Comment by mholt** [comment]
This is still not working for me. Dev tools shows that no event handlers are event bound to the helper. Does this work for helpers used in modals and/or in containers with `display: none`? The form helper may be rendered after the page loads. I assume Tabler is using a binding on `<body>` or similar, instead of selecting the individual elements just once?
