### ISSUE TITLE
[BUG] CDN imports not working

### ISSUE THREAD

**Issue by tteguayco** [tabler/tabler#766]
**Describe the bug**

After importing these two lines as the documentation states:

```html
<script src="https://unpkg.com/@tabler/core@latest/dist/js/tabler.min.js"></script>
```

```html
<link rel="stylesheet" href="https://unpkg.com/@tabler/core@latest/dist/css/tabler.min.css">
```

the elements seem not to be working properly. Maybe I am missing anything?

**Device**

 - Browser: Google Chrome 87
 - OS: Windows 10

**Screenshots**

How it looks on my website:

![image](https://user-images.githubusercontent.com/20015750/103443871-e3f23100-4c5a-11eb-9c82-c90b3fb99cec.png)

How it should look like:

![image](https://user-images.githubusercontent.com/20015750/103443878-f4a2a700-4c5a-11eb-98ea-f7b88a4239db.png)

**Comment by FreexD** [comment]
Hi @tteguayco. Did you import bootstrap JS? 
```
<script src="./dist/libs/bootstrap/dist/js/bootstrap.bundle.min.js?1610486969"></script>
```

**Comment by tteguayco** [comment]
Hi @FreexD, Sorry for the delay. I solved the issue by adding the following css and js files:

* CSS:
```html
<link rel="stylesheet" href="./assets/vendors/tabler/css/tabler.min.css">
<link rel="stylesheet" href="./assets/vendors/tabler/css/tabler-flags.min.css">
<link rel="stylesheet" href="./assets/vendors/tabler/css/tabler-payments.min.css">
<link rel="stylesheet" href="./assets/vendors/tabler/css/tabler-vendors.min.css">
<link rel="stylesheet" href="./assets/vendors/tabler/css/demo.min.css">
```
* JS:
```html
<script src="./assets/vendors/jquery/js/jquery-3.5.1.min.js"></script>
<script src="./assets/vendors/ace/ace.js"></script>
<script src="./assets/vendors/tabler/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="./assets/vendors/tabler/js/tabler.min.js"></script>
```

I took them from the [demo](https://preview.tabler.io/) page.

**Comment by kikikiblue** [comment]
Thanks for great template!!

CDN is not working as expected.

https://unpkg.com/@tabler/core@latest/dist/js/tabler.min.js -> it redirects to Tabler v1.0.0-alpha.12. 
https://unpkg.com/@tabler/core@latest/dist/css/tabler.min.css -> it also redirects to Tabler v1.0.0-alpha.12

I guess it should be alpha.22

minified css is working like documentation but tabler.css is weird.
If you include 'https://unpkg.com/@tabler/core@1.0.0-alpha.22/dist/css/tabler.css' for debuging, alert class is applied like this.

```
.alert {
    position: relative;
    padding: 1rem 1rem;
    margin-bottom: 1rem;
    border: 1px solid transparent;
    border-radius: 3px;
}

```
if you include tabler.min.css, it works well 

```
.alert {
    --tblr-alert-color: #656d77;
    background: #fff;
    border: 1px solid rgba(101,109,119,.16);
    border-left: .25rem solid var(--tblr-alert-color);
    box-shadow: rgba(35,46,60,.04) 0 2px 4px 0;
} 

```
I am sorry that I can't explain well because of my poor css/front-end skill 

Thanks anyway.

**Comment by codecalm** [comment]
@kikikiblue @tteguayco i've alreade change `latest` tag to newest version of tabler :)
