### ISSUE TITLE
[FEATURE] Bring back data-mask-reverse="true"

### ISSUE THREAD

**Issue by naq2** [tabler/tabler#791]
Hello again,

Would it be possible to bring back the « data-mask-reverse="true" » option for input-masks?
It used to work in the « old » version of Tabler and it was great to format currencies.

Thanks again for all the great work.

Take care.

——naq2

**Comment by FreexD** [comment]
Hi @naq2. We're switching from https://igorescobar.github.io/jQuery-Mask-Plugin/docs.html to https://imask.js.org/ for tabler 1.0 release because the latter does not have a dependency on jQuery. I'm afraid that If imask does not support the option, it will no longer be available out of the box in tabler. Could you try to submit an issue there https://github.com/uNmAnNeR/imaskjs ? Maybe they will implement it and we can upgrade the version in tabler to make it work :) The workaround would be to install https://github.com/igorescobar/jQuery-Mask-Plugin in your project and use it instead of imask :)
