### ISSUE TITLE
[BUG] Responsive Table got scroll issue with action menu

### ISSUE THREAD

**Issue by Smilefounder** [tabler/tabler#876]
**Describe the bug**
Demo: https://preview.tabler.io/tables.html
![image](https://user-images.githubusercontent.com/3785721/122602069-6b621e00-d09c-11eb-99c0-ed81b02301e1.png)

![image](https://user-images.githubusercontent.com/3785721/123677547-73297b80-d86f-11eb-82a7-4ed7d0c5e694.png)

**Comment by Smilefounder** [comment]
@codecalm kindly helps advice on this issue.
![image](https://user-images.githubusercontent.com/3785721/123677425-4e350880-d86f-11eb-88df-7b396828fa97.png)

**Comment by cavasinf** [comment]
Still an issue in `1.0.0-beta10`.
Possible workaround is to remove the responsiveness of the div table container `table-responsive`.

![image](https://user-images.githubusercontent.com/25293190/174046284-5783773e-5fa1-4d88-ba0d-2314f5bcfda8.png)

**Comment by kevinpapst** [comment]
This is not a tabler issue, but bootstrap itself:
https://getbootstrap.com/docs/5.3/content/tables/#responsive-tables

Pay attention to the last sentence in the yellow box:
<img width="839" alt="Bildschirmfoto 2023-05-14 um 23 52 50" src="https://github.com/tabler/tabler/assets/533162/a036d898-2a15-4640-ac93-1ebcdf6b70a4">

You can use bootstrap classes like `dropdown-menu-end` to align the boxes inside the table, so the issue is "hidden":
https://getbootstrap.com/docs/5.3/components/dropdowns/#menu-alignment
