### ISSUE TITLE
[BUG] Scrollbar and track always visible on chrome

### ISSUE THREAD

**Issue by ionutantohi** [tabler/tabler#966]
**Describe the bug**

Scrollbar and its track are always visible on Chrome even if the mouse is outside browser window and not scrolling. In beta 4, the scrollbar was hidden once you finished scrolling

This behaviour started with v1.0.0-beta5

**Device**
 - Browser Chrome Version 96.0.4664.93 (Official Build) (x86_64)
 - OS: macoS Big Sur

**Screenshots**
![image](https://user-images.githubusercontent.com/4609521/145988097-3f82f7f1-8a34-41bf-8426-65fc85ea9c2b.png)

**Comment by ionutantohi** [comment]
The screenshot above was taken when dark mode was enabled to show the efect. This happens non dark mode too.

**Comment by joao-uefrom** [comment]
I managed to solve this just removing it from the css:

`body {
...
  overflow-y: scroll;
...
}`

I don't know if it's correct, but it worked.

**Comment by ionutantohi** [comment]
@joao-uefrom  I tried to disable that using chrome devtools with no effect on my end.

**Comment by joao-uefrom** [comment]
@ionutantohi I didn't understand because it didn't work for you :(
![Captura de tela 2021-12-14 092256](https://user-images.githubusercontent.com/48249229/145998005-7168b69b-fdef-474c-ab1d-c37cc7f22924.png)

![Captura de tela 2021-12-14 092338](https://user-images.githubusercontent.com/48249229/145998028-3215aa4e-6217-4c31-98ae-fd23cb3e9517.png)

I tested it directly on preview.tabler.io

**Comment by ionutantohi** [comment]
This is exactly what I did :)
![image](https://user-images.githubusercontent.com/4609521/145998672-3cccfa5a-3b78-4e4b-9fd7-6c750850eff4.png)

**Comment by ionutantohi** [comment]
@codecalm  I think this behaviour was introduced within Dark improvments PR.


![image](https://user-images.githubusercontent.com/4609521/146637799-53531dba-4b6f-4432-affd-969a53bd735a.png)
