### ISSUE TITLE
[FEATURE] - Css switcher for  light and dark mode 

### ISSUE THREAD

**Issue by nejcdev** [tabler/tabler#969]
adding option to switch css between themes without refreshing page

**Comment by kevinpapst** [comment]
already available in the demo:

<img width="182" alt="Bildschirmfoto 2021-12-14 um 12 56 53" src="https://user-images.githubusercontent.com/533162/145993917-50f4c8d7-1860-44c9-acc1-4a5ef100d053.png">

**Comment by nejcdev** [comment]
Yeah i saw it with via url   what about local.storage?

**Comment by dheineman** [comment]
The dark/light mode toggle example on the tabler demo already use local storage to store the selected theme (which is why refreshing will persist your choice) you can view the key/value in (for example) the chrome element inspector and the related code in [demo.js](https://github.com/tabler/tabler/blob/4a2fa8cc8c8851bf9b51f97e9ec381a523a4c530/src/js/demo.js). 

The demo uses the url to toggle between them but you can create your own implementation that only uses javascript.

**Comment by rjd22** [comment]
Closing this since we have an example implementation. Developers are expected to roll their own when developing for their own application.
