### ISSUE TITLE
Input loader icon.

### ISSUE THREAD

**Issue by ghost** [tabler/tabler#97]
Input loader icon.

Is there a way to have `loader` animation (the one in dimmer for example) also in an form input component?

There is not yet in the demo or am I wrong?

**Comment by johnunclesam** [comment]
Maybe like this:

![image](https://user-images.githubusercontent.com/21275217/38817407-971943ac-4198-11e8-9335-481bd73a8b3f.png)

And in button like this:

![image](https://user-images.githubusercontent.com/21275217/38817435-a95ba30c-4198-11e8-9785-41c3f45fa1b9.png)

But I don't know how and where to push...

**Comment by codecalm** [comment]
good idea! I'll check it

**Comment by johnunclesam** [comment]
Maybe with animation changing from state to `loading` and not `loading`. But this is a NTH.

And maybe with some message in button, something like: "Saving O".

**Comment by isneezy** [comment]
I've noticed that this theme uses selectize.js and actually selectize.js adds a `.loading` class when doing ajax requests, but while i was using it with this theme it wasn't showing the loader/dimmer animation.
I think the @johnunclesam idea is great since it will integrate with the selectize.js too.
